name: eglinski
favicon: null
layout_spectrum: 0.8113135481253266
typography_spectrum: 0.5182988175656646
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6995523509103805
  lightness: 0.9755124705843627
  saturation: 0.4448764694388956
  rhythmicContrast: 0.9464490455575287
purpose: []
